<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Certificate</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            padding: 50px;
            border: 10px solid #1d4ed8;
            margin: 20px;
            color: #333;
        }
        h1 {
            font-size: 50px;
            color: #1e3a8a;
            margin-bottom: 10px;
        }
        h2 {
            font-size: 24px;
            margin-bottom: 40px;
            font-weight: normal;
        }
        p.name {
            font-size: 36px;
            font-weight: bold;
            text-decoration: underline;
            margin-bottom: 20px;
        }
        p.course {
            font-size: 28px;
            color: #2563eb;
            font-weight: bold;
            margin-top: 20px;
            margin-bottom: 40px;
        }
        .footer {
            margin-top: 50px;
            font-size: 14px;
            color: #666;
        }
        .date {
            margin-top: 30px;
            font-size: 18px;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <h1>CERTIFICATE OF COMPLETION</h1>
    <h2>This is to certify that</h2>
    <p class="name">{{ $certificate->user->name }}</p>
    <p>has successfully completed the course</p>
    <p class="course">{{ $certificate->course->title }}</p>
    <div class="date">
        Date of Issue: {{ \Carbon\Carbon::parse($certificate->issue_date)->format('F d, Y') }}
    </div>
    <div class="footer">
        Certificate Number: {{ $certificate->certificate_number }}<br>
        This certificate is automatically generated by the ESA Learning System.
    </div>
</body>
</html>
